In [1]:
import pandas as pd
df=pd.read_csv("job_salary_prediction_dataset.csv")
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [3]:
df.isna().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [6]:
# 5. Separate features and target
target = "salary"   # change this if your label column has another name
X = df.drop(columns=[target])
y = df[target]

In [7]:
print('X\n',X)

X
                  job_title  experience_years education_level  skills_count  \
0              AI Engineer                10        Bachelor             2
1             Data Analyst                 5        Bachelor            17
2       Frontend Developer                18             PhD             4
3         Business Analyst                19             PhD            13
4          Product Manager                15        Bachelor             7
...                    ...               ...             ...           ...
249995   Software Engineer                17             PhD             2
249996  Frontend Developer                20             PhD             7
249997    Business Analyst                 1        Bachelor            12
249998      Data Scientist                 0     High School             2
249999        Data Analyst                16         Diploma             2

             industry company_size   location remote_work  certifications
0          Healthcare       Medium      India      Hybrid               2
1             Telecom        Small  Australia          No               0
2               Media       Medium  Singapore          No               1
3              Retail       Medium     Canada         Yes               0
4       Manufacturing        Large     Sweden         Yes               0
...               ...          ...        ...         ...             ...
249995        Telecom   Enterprise      India          No               1
249996        Telecom      Startup     Remote          No               2
249997         Retail   Enterprise      India         Yes               0
249998     Consulting        Small     Sweden      Hybrid               5
249999     Technology       Medium         UK          No               5

[250000 rows x 9 columns]

In [8]:
y

0         109413
1          93764
2         148123
3         189123
4         165069
           ...
249995    127791
249996    154593
249997     75988
249998     90467
249999    133084
Name: salary, Length: 250000, dtype: int64

In [9]:
## convert objects to int

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [10]:
# -----  Split categorical into OHE vs Label -----
cat_cols = X.select_dtypes(include="object").columns

# Example rule: <=10 unique values → OHE, else LabelEncode
low_card_cols = [c for c in cat_cols if X[c].nunique() <= 10]
high_card_cols = [c for c in cat_cols if X[c].nunique() > 10]

print("OHE columns:", low_card_cols)
print("LabelEncode columns:", high_card_cols)

OHE columns: ['education_level', 'industry', 'company_size', 'location', 'remote_work']
LabelEncode columns: ['job_title']

In [11]:
# Apply One-Hot Encoding
X = pd.get_dummies(X, columns=low_card_cols, drop_first=True)

# Convert all boolean columns to integers (0/1)
X = X.astype({col: int for col in X.select_dtypes(include="bool").columns})

In [12]:
# Apply Label Encoding for high-cardinality columns
for col in high_card_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

In [13]:
X

,job_title,experience_years,skills_count,certifications,education_level_Diploma,education_level_High School,education_level_Master,education_level_PhD,industry_Education,industry_Finance,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,0,10,2,2,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,5,5,17,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,8,18,4,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
3,2,19,13,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,10,15,7,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,11,17,2,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
249996,8,20,7,2,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
249997,2,1,12,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
249998,6,0,2,5,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
249999,5,16,2,5,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [14]:
## Train-test split -----
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Final Train shape:", X_train.shape)
print("Final Test shape :", X_test.shape)

Final Train shape: (200000, 32)
Final Test shape : (50000, 32)

In [15]:
## Build the model

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

L= Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

L.fit(X_train, y_train)


L=LinearRegression()
L.fit(X_train, y_train)

LinearRegression()

In [16]:
## Predict the model
y_test_pred=L.predict(X_test)
y_train_pred=L.predict(X_train)

In [17]:
df=pd.DataFrame({'Actual':y_test,'Predicted':y_test_pred,'Diffrence':y_test-y_test_pred})
df

        Actual      Predicted     Diffrence
38683   164009  144345.156474  19663.843526
64939    79594   85044.042496  -5450.042496
3954     74090   76810.321526  -2720.321526
120374  177193  139853.366980  37339.633020
172861  120012  121749.111146  -1737.111146
...        ...            ...           ...
179545  136275  141257.583820  -4982.583820
222647  168515  166616.084440   1898.915560
171823  176232  178281.703316  -2049.703316
135782  152933  150697.517728   2235.482272
208380  116585  117739.937196  -1154.937196

[50000 rows x 3 columns]

In [18]:
# Note: you can check the accuracy of your model with both training dataset and testing dataset

#RMSE AND SCORE ON TRAINING DATASET (160 RECORDS)
from sklearn import metrics as m 
y_train_pred= L.predict(X_train) # training dataset(x_train and y_train)
print("RMSE:",np.sqrt(m.mean_squared_error(y_train,y_train_pred)))# Error on training dataset
print("R-SQUARED:",m.r2_score(y_train, y_train_pred)) # accuracy on training dataset

RMSE: 16710.685331312117
R-SQUARED: 0.8007827020812139

In [19]:
#RMSE AND SCORE ON TESTING DATASET (40 RECORDS)
y_test_pred= L.predict(X_test)
print("RMSE:",np.sqrt(m.mean_squared_error(y_test,y_test_pred))) 
print("R-SQUARED:",m.r2_score(y_test, y_test_pred))# accuracy on testing dataset

RMSE: 16668.546274166285
R-SQUARED: 0.8000951833496535

In [20]:
## Variance = RMSE of training data - RMSE of testing data
print('Bias result\n',16668.546274166285-16710.685331312117)
## Variance = R-square of testing - R-square of training
print('R-square result\n',0.8000951833496535-0.8007827020812139)

Bias result
 -42.13905714583234
R-square result
 -0.0006875187315604769

In [21]:
print(10*37407.952729/100)

3740.7952729

In [22]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [31]:
DC=DecisionTreeRegressor()
DC.fit(X_train, y_train)

DecisionTreeRegressor()

In [32]:
## Predict the model
y_test_pred=DC.predict(X_test)
y_train_pred=DC.predict(X_train)

In [33]:
#RMSE AND SCORE ON TESTING DATASET (40 RECORDS)
y_test_pred= DC.predict(X_test)
print("RMSE:",np.sqrt(m.mean_squared_error(y_test,y_test_pred))) 
print("R-SQUARED:",m.r2_score(y_test, y_test_pred))# accuracy on testing dataset

RMSE: 9728.582768843313
R-SQUARED: 0.9319031591408895

In [34]:
RF=RandomForestRegressor()
RF.fit(X_train, y_train)

RandomForestRegressor()

In [35]:
## Predict the model
y_test_pred=RF.predict(X_test)
y_train_pred=RF.predict(X_train)

In [36]:
#RMSE AND SCORE ON TESTING DATASET (40 RECORDS)
y_test_pred= RF.predict(X_test)
print("RMSE:",np.sqrt(m.mean_squared_error(y_test,y_test_pred))) 
print("R-SQUARED:",m.r2_score(y_test, y_test_pred))# accuracy on testing dataset

RMSE: 6752.840498534448
R-SQUARED: 0.967190410851827

In [38]:
import joblib
joblib.dump(RF,'RF_sal.pkl')

['RF_sal.pkl']